version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.0.2
    volumes:
      - ./meili-data:/meili_data
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: development
